# Generated by Django 3.2.8 on 2021-10-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_notaaula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaaula',
            name='nota',
            field=models.CharField(choices=[('p', 'Péssimo'), ('r', 'Ruim'), ('re', 'Regular'), ('b', 'Bom'), ('o', 'Ótimo')], max_length=50),
        ),
    ]
